services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  R3H6\FormTranslator\:
    resource: '../Classes/*'

  R3H6\FormTranslator\Controller\TranslationController:
    public: true

  extensionconfiguration.form_translator.libreTranslate.host:
    class: 'string'
    factory: ['@TYPO3\CMS\Core\Configuration\ExtensionConfiguration', 'get']
    arguments: ['form_translator', 'libreTranslate/host']

  extensionconfiguration.form_translator.libreTranslate.apiKey:
    class: 'string'
    factory: ['@TYPO3\CMS\Core\Configuration\ExtensionConfiguration', 'get']
    arguments: ['form_translator', 'libreTranslate/apiKey']

  extensionconfiguration.form_translator.languageFilesDirectory:
    class: 'string'
    factory: ['@TYPO3\CMS\Core\Configuration\ExtensionConfiguration', 'get']
    arguments: ['form_translator', 'languageFilesDirectory']

  R3H6\FormTranslator\Service\LibreTranslateTranslationService:
    arguments:
      $host: '@extensionconfiguration.form_translator.libreTranslate.host'
      $apiKey: '@extensionconfiguration.form_translator.libreTranslate.apiKey'


  R3H6\FormTranslator\Service\FormService:
    arguments:
      $locallangPath: '@extensionconfiguration.form_translator.languageFilesDirectory'

  R3H6\FormTranslator\Service\TranslationServiceInterface: '@R3H6\FormTranslator\Service\LibreTranslateTranslationService'


  TYPO3\CMS\Core\Cache\Frontend\FrontendInterface $l10nCache: '@cache.l10n'
  cache.l10n:
    class: 'TYPO3\CMS\Core\Cache\Frontend\FrontendInterface'
    factory: ['@TYPO3\CMS\Core\Cache\CacheManager', getCache]
    arguments: ['l10n']

  R3H6\FormTranslator\Command\CreateXliffCommand:
    tags:
      - name: 'console.command'
        command: 'form:create:xliff'

  R3H6\FormTranslator\EventListener\RemoveEmptyItems:
    tags:
      - name: event.listener
        identifier: 'form_translator.removeEmptyItems'
        event: R3H6\FormTranslator\Event\AfterParseFormEvent

  R3H6\FormTranslator\Property\TypeConverters\SiteLanguageConverter:
    tags:
      - name: extbase.type_converter
        priority: 1
        target: TYPO3\CMS\Core\Site\Entity\SiteLanguage
        sources: integer, string

  R3H6\FormTranslator\Property\TypeConverters\ItemCollectionConverter:
    tags:
      - name: extbase.type_converter
        priority: 1
        target: R3H6\FormTranslator\Translation\ItemCollection
        sources: array
