base: 'https://typo3-form-translator.ddev.site/'
languages:
  -
    title: English
    enabled: true
    languageId: 0
    base: /
    locale: en_US.UTF-8
    navigationTitle: English
    flag: us
  -
    title: French
    enabled: true
    locale: fr_FR
    hreflang: ''
    base: /fr/
    websiteTitle: ''
    navigationTitle: Français
    fallbackType: strict
    fallbacks: ''
    flag: fr
    languageId: 1
  -
    title: 'Chinese (Simplified)'
    enabled: true
    locale: zh_CN
    hreflang: ''
    base: /cn/
    websiteTitle: ''
    navigationTitle: 汉语
    fallbackType: strict
    fallbacks: ''
    flag: cn
    languageId: 2
  -
    title: Canada
    enabled: true
    locale: fr_CA
    hreflang: ''
    base: /fr-ca/
    websiteTitle: ''
    navigationTitle: Canada
    fallbackType: strict
    fallbacks: ''
    flag: ca
    languageId: 3
rootPageId: 1
websiteTitle: ''
