base: 'https://typo3-form-translator.ddev.site/'
languages:
  -
    title: English
    enabled: true
    languageId: 0
    base: /
    locale: en_US
    navigationTitle: English
    flag: us
    hreflang: ''
    websiteTitle: ''
  -
    title: German
    enabled: true
    locale: de_DE
    hreflang: ''
    base: /de/
    websiteTitle: ''
    navigationTitle: Deutsch
    fallbackType: strict
    fallbacks: ''
    flag: de
    languageId: 1
    typo3Language: de
  -
    title: 'German (Swiss)'
    enabled: true
    locale: de_CH
    hreflang: ''
    base: /de-CH/
    websiteTitle: ''
    navigationTitle: 'Deutsch Schweiz'
    fallbackType: strict
    fallbacks: '1'
    flag: ch
    languageId: 2
  -
    title: 'German (Austria)'
    enabled: true
    locale: de_AT
    hreflang: ''
    base: /de-AT/
    websiteTitle: ''
    navigationTitle: Deutsch
    fallbackType: strict
    fallbacks: ''
    flag: at
    languageId: 3
  -
    title: 'English (UK)'
    enabled: true
    locale: en_GB
    hreflang: ''
    base: /en-gb/
    websiteTitle: ''
    navigationTitle: 'English (UK)'
    fallbackType: strict
    fallbacks: ''
    flag: gb
    languageId: 4
rootPageId: 1
websiteTitle: ''
